version: "3"

services:
  web:
    build: .
    container_name: tarder_app
    volumes:
      - .:/traders
    ports:
      - "8000:8000"
    links:
      - "db:db"
    depends_on:
      - db
    env_file: ./config/web.dev
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: ./config/db.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
