version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "eva987987"
      POSTGRES_DB: "traderdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis-server:
    image: redis:latest
    command: 'redis-server'
    ports:
      - "6379:6379"
volumes:
  postgres-data:
