version: "3"

services:
  web:
    build: .
    container_name: tarder_app
    volumes:
      - .:/traders
    ports:
      - "8000:8000"
    links:
      - "db:db"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "eva987987"
      POSTGRES_DB: "traderdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
