# Generated by Django 3.1.4 on 2021-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chem_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'chemical type',
            },
        ),
    ]
