# Generated by Django 3.1.4 on 2021-01-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0001_initial'),
    ]

    def add_chemicals(apps, schema_editor):
        ChemicalTypeModel = apps.get_model('tradersapi', 'ChemicalTypeModel')
        ChemicalTypeModel.objects.bulk_create([
            ChemicalTypeModel(chem_type='prime/virgin'),
            ChemicalTypeModel(chem_type='reprocessed/recycled'),
            ChemicalTypeModel(chem_type='scrap'),
            ChemicalTypeModel(chem_type='masterbatch'),
            ChemicalTypeModel(chem_type='compunds')
        ])

    operations = [
        migrations.RunPython(add_chemicals)
    ]
