# Generated by Django 3.1.4 on 2021-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0004_auto_20210106_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalmodel',
            name='chemical_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
