# Generated by Django 3.1.4 on 2021-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0006_userprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/default_profile_pic.png', null=True, upload_to='upload/'),
        ),
    ]
