# Generated by Django 3.1.4 on 2021-01-27 18:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0007_auto_20210127_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
