# Generated by Django 3.1.4 on 2021-02-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0008_auto_20210127_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='tradersapi.chemicalmodel', verbose_name='chemicals')),
                ('chemical_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='tradersapi.chemicaltypemodel', verbose_name='chemicals_type')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chemical_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='tradersapi.chemicalproduct')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tradersapi.userprofilemodel')),
            ],
        ),
    ]
