# Generated by Django 3.1.4 on 2021-03-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0009_auto_20210226_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
