# Generated by Django 3.1.4 on 2021-03-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0010_delete_userproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('1', 'KG'), ('2', 'POUND'), ('3', 'DRUM'), ('4', 'BAG')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Archived'), ('0', 'Processing')], max_length=1)),
                ('post_type', models.CharField(choices=[('0', 'sell'), ('1', 'buy')], max_length=1)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='tradersapi.userprofilemodel')),
            ],
        ),
    ]
