# Generated by Django 3.1.4 on 2021-03-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0011_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='chemical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='tradersapi.chemicalmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='chemical_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='tradersapi.chemicaltypemodel'),
            preserve_default=False,
        ),
    ]
