# Generated by Django 3.1.4 on 2022-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersapi', '0015_auto_20220317_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
